
[Executed at: Sun Mar 18 23:53:14 PDT 2018]

Test case 1: area_square
Pass:  True
Test case 2: area_square
Pass:  True
Test case 3: area_square
Pass:  True
Traceback (most recent call last):
  File "/home/ccc_v1_c79523__48809/asn24778_45/asn24779_1/asnlib/autograde.py", line 14, in <module>
    score=runtest.main()
  File "/home/ccc_v1_c79523__48809/asn24778_45/asn24779_1/asnlib/runtestcases.py", line 63, in main
    stu_work=getattr(__import__(work_package, fromlist=fun_name), f)
AttributeError: module 'q3_work' has no attribute 'vol_frustum'
Command exited with non-zero status 1
